### ISSUE TITLE
Adding Offline validation when internet comes back

### ISSUE THREAD

**Issue by willmendesneto** [manosim/gitify#209]
When the internet is off, we have a user feedback, but when the internet comes back we need to click on the update button to make it work again. How we have access for OnLine HTML5 API we can automate this behaviour, improving the user experience.

**Comment by manosim** [comment]
Hello @willmendesneto ! I was planning for a new release soon and this is a nice feature to have and great timing as well! I've implemented this functionality and will be included in `1.1.0`. 🎉

**Comment by willmendesneto** [comment]
WOW! Thanks @manosim !This is a great news!
