### ISSUE TITLE
feature: change icon color if there are any notifications

### ISSUE THREAD

**Issue by kpurdon** [manosim/gitify#217]
I feel like the pre-1.0 version mac icon changed to green if there were any active notifications. Right now the icon (with mac dark-theme) just stays white regardless of there being, or not being any active notifications.

If there are notifications either:
- change the color of the icon
- add a number to show number of open notifications
- something else to indicate active notifications w/o opening the tool

**Comment by kpurdon** [comment]
Just noticed that it turns green immediately when I get a notification but does not stay green, even if there are still active items.

**Comment by manosim** [comment]
Hi @kpurdon! This was fixed during the weekend in #212 and will be included in the next release! Hopefully this week!

**Comment by manosim** [comment]
Hey @kpurdon! Version 1.1.0 is out so the update should fix this one!
