### ISSUE TITLE
Not Receiving Notifications

### ISSUE THREAD

**Issue by ChristianWalker19** [manosim/gitify#220]
Hi,

I installed gitify and set up my account but I'm still not receiving any notifications.  Please see my screenshot,
![screen shot 2016-09-12 at 10 55 26 am](https://cloud.githubusercontent.com/assets/15202278/18442767/a11d28d6-78d7-11e6-8a4f-3ec9b28092a9.png)

Thanks,
Chris

**Comment by simonsmith** [comment]
Hmm, I'm getting the same issue since moving to 1.0. I can't offer more than that in detail. If there is some way I can debug please let me know.

**Comment by manosim** [comment]
Hello @simonsmith! I am planning to release a new version today that will allow debugging so hope this will help us tackle this issue. Will let you know once it is out!

**Comment by ChristianWalker19** [comment]
Hey, @simonsmith  @manosim I think it may be an organization setting that's the problem.  I tested it with another organization and it worked.

**Comment by simonsmith** [comment]
@ChristianWalker19 Do you know what the setting was?

**Comment by ChristianWalker19** [comment]
@simonsmith I'm looking now. I actually just got your reply from the gitify app.

**Comment by ChristianWalker19** [comment]
@manosim is this an approved third party application?  Based on [this](https://help.github.com/articles/connecting-with-third-party-applications/) it looks like third-party applications immediately lose access to the organization's resources.  When you create a new organization, third-party applications are restricted by default. **Organization admins can disable third-party application restrictions at any time.**

**Comment by manosim** [comment]
Yes that is correct - If you application is **not approved** from your organisation admin, then you **will not receive** any notifications specific to this org's repositories. To check if "gitify" is approved by your organisation you can go to [https://github.com/settings/applications](https://github.com/settings/applications), then click on **Gitify** and scroll to **Organization access**. Hope this helps!

![kfwaaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/6333409/18592568/845fc806-7c2f-11e6-9b2e-f87c1a8fe067.png)

**Comment by ChristianWalker19** [comment]
@manosim I was able to enable gitify from my personal account as an approved application. Thanks!

**Comment by simonsmith** [comment]
@manosim That seems to be the issue yes. I've sorted my permissions.

I think this would be a great addition to the README as I had no idea to check that page. Happy to PR it if you agree.

Thanks for your help though

**Comment by simonsmith** [comment]
How about allowing access via an API token, much like the [Github for Chrome](https://github.com/sindresorhus/notifier-for-github-chrome) extension.

I noticed that I get notifications via that extension that Gitify could not pick up. Is that even an option?

**Comment by manosim** [comment]
@simonsmith Sure, feel free to open a PR and add a new section "FAQ" before the *Contributing* section.

About allowing users to provide their API token, I don't think that it would be the best path, since it would break the auth flow and would make things more "complicated" (instead of login, create a token and type it here)? Also the login flow works fine with Gitify, it is just the org permissions that have to be set(the first time you login, GitHub asks for permissions). Hope this makes sense!

**Comment by simonsmith** [comment]
@manosim Understood 👍

**Comment by manosim** [comment]
@simonsmith As promised, version 1.1.0 is now out and in case anything goes wrong you can debug using `alt+cmd+i`.

**Comment by simonsmith** [comment]
Good job on the debug addition but it also looks like the FAQ change has been lost.

**Comment by manosim** [comment]
It's still there (on the readme)? [https://github.com/manosim/gitify#faq](https://github.com/manosim/gitify#faq)

**Comment by simonsmith** [comment]
Bizarre. Definitely couldn't see it earlier and it said the README was updated 19 days ago. Maybe github playing up

All good now 👍
