### ISSUE TITLE
React Native MacOSX version

### ISSUE THREAD

**Issue by mrcasals** [manosim/gitify#248]
Hi!

First of all, thanks for the work you've put into this, the app is really useful. The only drawback is that it's built with electron, which is really bloated (it includes an entire copy of Chromium). Since there's already a mobile version for this built with React Native, and considering there's this [`react-native-macos`](https://github.com/ptmt/react-native-macos) project, how hard would it be to port this app to a native app using this React Native fork?

I guess most of the codebase could be reused (wither from this project or from the mobile version), and this would reduce the amount of resources needed by this app.

Thanks!

**Comment by manosim** [comment]
Gitify went recently through a massive rewrite so quite a few things changed since the first couple of releases. Closing this one due to inactivity.
