### ISSUE TITLE
Dialing to manos.im

### ISSUE THREAD

**Issue by Fastidious** [manosim/gitify#255]
Any reason why this application is dialing to manos.im (tcp/443), and aboutme.google.com (tcp/443), when connecting it to GitHub?

**Comment by manosim** [comment]
Hello @Fastidious! I am not sure what do you mean - is it actually making a request? `manos.im` is my personal website but neither this or `aboume.google.com` is even included in the source code. I will be more than happy to investigate it further.

**Comment by Fastidious** [comment]
@manosim yes, it was making a request. The list changes (more than one FQDN pointing to same IP). It is  weird, I just deleted the app, and re-added it, and this time I did not get a dial to `manos.im`, but:

- api.github.com ✅ 
- collector.githubapp.com ✅ 
- chrome.google.com ❓ 
- twitter.github.io ❓ 
- www.github.com

All on TCP/443.

**Comment by manosim** [comment]
Closing this one because of inactivity - let me know if that's still the case.
