### ISSUE TITLE
feature request: Mark all read

### ISSUE THREAD

**Issue by smileytechguy** [manosim/gitify#262]
Not just 1 repository, but all

**Comment by michelleyschen** [comment]
Close because the issue already exist here: https://github.com/manosim/gitify/issues/262

**Comment by smileytechguy** [comment]
@michelleyschen this is #262?

**Comment by michelleyschen** [comment]
oops, I mean #249, sorry about that.

**Comment by smileytechguy** [comment]
Alright, thanks.  Closing
