### ISSUE TITLE
ux bug: persistent scrollbar

### ISSUE THREAD

**Issue by smileytechguy** [manosim/gitify#263]
For those who have the scrollbar to always show, causing the content area to be decreased by a few pixels when scrollable, marking many done at once reduces the list, removing the scrollbar and moving the done button just a little out of reach, instead opening the repository in the browser

**Comment by manosim** [comment]
That shouldn't be the case in version 3.0.0 - the app went through a massive rewrite. Let me know if that's still the case and I'm happy to reopen this issue.
