### ISSUE TITLE
Steps to login with enterprise github

### ISSUE THREAD

**Issue by ayushgoel1610** [manosim/gitify#269]
I see the readme talks about github enterprise support post version 1.0.0. 

However no where do I see the steps to login with my enterprise account. By default the login page  redirects to `github.com`.

**Comment by manosim** [comment]
Hello @ayushgoel1610! Can you try downloading version 2? Version 2 was just released and is the first one to support GitHub Enterprise. Let me know if you find any bugs! I did test GitHub Enterprise extensively but not using it day to day so I might have missed something.
