### ISSUE TITLE
Wrong PR when clicking notification

### ISSUE THREAD

**Issue by bquorning** [manosim/gitify#274]
I’ve seen quite a few times now that clicking a notification from Gitify will open the GitHub page for an older pull request with an identical title – not the recent pull request.

I haven’t made any attempt at reproducing the issue, sorry.

**Comment by bquorning** [comment]
This is still happening, by the way.

**Comment by manosim** [comment]
Now that version 3 is out, that shouldn't be the case any more. Let me know if this occurs again and I'll be happy to investigate.
