### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by brkattk** [manosim/gitify#282]
I was recently looking in Activity Monitor and noticed that Gitify Helper was using over 900MB of memory. :eyes:

I'm using 1.1.0 and have ~50 unread notifications across 11 different repos. If i keep an eye on Activity Monitor, I can watch the used memory slowly rise and never fall for Gitify Helper

**Comment by manosim** [comment]
Hello @brkattk! Not sure on how to approach this one since it has to do with Electron. In version 2, I have updated electron to the latest version(v1 uses a pretty old version of electron) so I would think that there have been some improvements around this?
