### ISSUE TITLE
network detect recovery

### ISSUE THREAD

**Issue by atian25** [manosim/gitify#284]
![image](https://cloud.githubusercontent.com/assets/227713/25319846/47c9572a-28d4-11e7-8c0c-424bcadebe80.png)

**Comment by necramirez** [comment]
This is a bit of an inconvenience, as the only way to reconnect is to Force Quit Gitify and run it again.

**Comment by manosim** [comment]
Hello! This has beed fixed in v2, sorry about that! Will release as soon as we have GitHub Enterprise support which is work in progress!

**Comment by manosim** [comment]
Hello everyone! Version 2 is now out so this one should be fixed!
