### ISSUE TITLE
No way to recover from lost connection

### ISSUE THREAD

**Issue by bradzacher** [manosim/gitify#290]
If the app ever gets into a state where it finds no internet connection, there is no way to reset it / there is no automatic recovery. You are stuck with the attached screen.

The only way to fix this that I've found is to quit and restart gitify.

![screen shot 2017-05-29 at 4 32 45 pm](https://cloud.githubusercontent.com/assets/7462525/26538843/851507a4-448c-11e7-894f-b4e004ce6aa3.png)

**Comment by manosim** [comment]
Hello @bradzacher! Thank you for opening the issue! This is related to #284 and it has been fixed in version 2 which will be out soon!

**Comment by manosim** [comment]
Hello @bradzacher! Version 2 is now out so this one should be fixed!
