### ISSUE TITLE
Placement is off on macOS

### ISSUE THREAD

**Issue by ahoarau** [manosim/gitify#292]
When the  "auto hide" toolbar is enabled, gitify appears behind it.
![image](https://user-images.githubusercontent.com/703240/27194233-233f14b0-5202-11e7-9ed0-8a94d7ca2ed8.png)

**Comment by manosim** [comment]
Hello @ahoarau! Version 2 is now out and it is a completely rewrite (the app is not on the tray anymore) so you should not have this issue with v2 and onwards. Let me know if you have any further issues!
