### ISSUE TITLE
Issues Authenticating

### ISSUE THREAD

**Issue by raoulj** [manosim/gitify#295]
I make an account as direct when getting gitify via brew (`brew cask install gitify`).  I get the following response: 
![screen shot 2017-06-18 at 4 59 41 pm](https://user-images.githubusercontent.com/12823489/27264215-e2567770-5447-11e7-8b7a-f25f4b756375.png)
Everything seems approved but it is not letting me create an account?

**Comment by manosim** [comment]
Hello @raoulj! Can you try downloading version 2 from [github releases](https://github.com/manosim/gitify/releases/tag/2.0.0) since the cask is not updated yet(I wasn't the one to upload the cask and I am not sure on how to update it)?

**Comment by raoulj** [comment]
Ok!  I just downloaded and I found that I had the same issue.  Notably, however, the new download cached my attempt at login from my previous installation.  I click the "Login to GitHub" button at the home screen and get immediately taken to the screen above.  This is identical behavior to the cask installation.  Would this shared datastore be the cause of the issue and getting me to some invalid state?

**Comment by manosim** [comment]
Yes both versions use the same "storage" so it realises you already logged in in that window. Can you describe the steps when you first downloaded gitify and tried to login so I can reproduce the error?

**Comment by raoulj** [comment]
Sure thing.

- I open the app installed via cask.  
- I select "Login to Github."  I enter my username and password.  (For what it's worth, I got my password wrong on the first attempt)
- I succeed on providing these credentials, then I am asked to provide 2-Factor Authentication.  I do so.  I click enter.
- I am navigated to the above screen, with no means of navigating to any other view.

**Comment by manosim** [comment]
Ok I think I'm getting closer. Once you are stuck on this screen can you open the devtools (of the github.com window) by press `alt+cmd+i` and take a screenshot ?

**Comment by manosim** [comment]
Ok I was able to reproduce it and fix it at #296. Will make a new release tomorrow as it is pretty late here. Will let you know once it's done. Thank you for reporting this issue! 👍

**Comment by raoulj** [comment]
Awesome!  Glad to help!

**Comment by manosim** [comment]
Hello @raoulj! [Version 2.0.1](https://github.com/manosim/gitify/releases/tag/2.0.1) is now out! Hope you can now login!

**Comment by taylor325** [comment]
Hello i downloaded 2.0.2 and i have a login issue :(
Error message on top via GitHub: "Please note that GitHub no longer supports your web browser.
We recommend upgrading to the latest Google Chrome or Firefox."

**Comment by JakeSidSmith** [comment]
@taylor325 I believe you are referring to this issue: https://github.com/manosim/gitify/issues/355

There are a couple of solutions in that thread.

**Comment by taylor325** [comment]
@JakeSidSmith Yes! Thank you! :)
