### ISSUE TITLE
support hide to tray at 2.0

### ISSUE THREAD

**Issue by atian25** [manosim/gitify#297]

**Comment by AlecRust** [comment]
Hide to tray? As in the notifications would still be visible from the tray in a dropdown as before?

If that's what this issue is for, +1.

**Comment by atian25** [comment]
don't show at dock it needed.

whether show as dropdown is optional.

**Comment by AlecRust** [comment]
Sorry, I don't follow. Opened https://github.com/manosim/gitify/issues/298 for making these visible from the dropdown again.
