### ISSUE TITLE
Update Prompt Everytime the App Starts

### ISSUE THREAD

**Issue by bradynpoulsen** [manosim/gitify#302]
I'm using 2.0.1 on macOS 10.12.5.

Every time the Gitify app, it prompts for me to Update and Restart. I do the update and shutdown the Gitify app and open it back up and it immediately prompts for another update but it has yet to change from version 2.0.1

**Comment by twhite96** [comment]
Same happening for me.

**Comment by manosim** [comment]
With version 3 we've moved to electron builder which comes with its own "auto-update" library so that shouldn't be the case any more 😄
