### ISSUE TITLE
OS X Private notification missing

### ISSUE THREAD

**Issue by uhlhosting** [manosim/gitify#305]
Hello

I am using both on iPhone Gitify, and OS X and none of my devices receive the private notifications!

http://prntscr.com/foh319

Looking forward for a quick reply to this. Since both Private repos or public should have notifications.

**Comment by manosim** [comment]
Hello @uhlhosting! Are your repositories part of an organization? If so, did you try [this](https://github.com/manosim/gitify#my-notifications-arent-showing)?

**Comment by chevinbrown** [comment]
@manosim that link worked for me. Perhaps we can add that to the readme as it's not quite clear...

**Comment by chevinbrown** [comment]
Also recommend closing stale issues such as tis. 😸
