### ISSUE TITLE
brew cask install gitify - old version.

### ISSUE THREAD

**Issue by danieldbird** [manosim/gitify#306]
brew cask install gitify is still an older version and has the following issue. 

![image](https://user-images.githubusercontent.com/2720368/27773717-2ba35aaa-5fd4-11e7-9c06-2c1b44561c71.png)

**Comment by matchai** [comment]
Looking at the installation logs, it appears to be installing the latest release, 2.0.2.
It looks like someone either ran a `cask-repair` or it's unrelated to the issue you were encountering on the older version.

<img width="632" alt="image" src="https://user-images.githubusercontent.com/4658208/31392458-4fc92966-ada7-11e7-8d88-ed5c9a6718d6.png">

**Comment by manosim** [comment]
This should be fixed once https://github.com/Homebrew/homebrew-cask/pull/76821/files gets merged with v3.0.0.
