### ISSUE TITLE
gitify appears off screen 

### ISSUE THREAD

**Issue by aioue** [manosim/gitify#308]
Latest v2

This is the bottom left corner of my screen. OS X 10.12.4
<img width="92" alt="screen shot 2017-07-10 at 22 41 09" src="https://user-images.githubusercontent.com/1254905/28041399-287878d6-65c1-11e7-91be-e1bdc68a69c9.png">

**Comment by manosim** [comment]
Gitify went through a massive rewrite and this shouldn't be the case in v3.0.0. Let me know if it happens and will be happy to reopen. 😄
