### ISSUE TITLE
Unclear how to limit gitify to only specific organizations on my account

### ISSUE THREAD

**Issue by erikmellum** [manosim/gitify#310]
I only want gitify to give me notifications about certain organizations I'm part of and its not at all clear to me how to do this. Please let me know if I missed a doc somewhere or if this just isn't possible.

Thanks!

**Comment by JakeSidSmith** [comment]
You can change which repositories you're watching [here](https://github.com/watching), but apart from toggling whether you want to show only participating or all notifications, Gitify cannot be configured separately from this.

**Comment by erikmellum** [comment]
That makes sense, thanks @JakeSidSmith. 

Thats reasonable, but I probably will stay off gitify for now. I like watching many repos, I just only want push notifications for a subset of them.

That's more my problem than gitifys. Closing this out.
