### ISSUE TITLE
Gitify is eating my api rate limit

### ISSUE THREAD

**Issue by callicles** [manosim/gitify#312]
Hi!

I have been using `gitify` for some time and been quite happy with it so far. But now, it is eating my github rate limit. To the point where it prevents me from logging into other services.

Is there a way to prevent that from happening?

Thank you

**Comment by callicles** [comment]
Just updated to version 2, maybe that will solve the issue

**Comment by JakeSidSmith** [comment]
@callicles this was an issues in an earlier version of Gitify, but should be solved in v2. :)

**Comment by callicles** [comment]
perfect, thx!
