### ISSUE TITLE
Show news from Dashboard

### ISSUE THREAD

**Issue by a3f** [manosim/gitify#315]
Is there some way to display those in gitify?

<img width="568" alt="github.com" src="https://user-images.githubusercontent.com/5204368/29771055-3de189ae-8bf2-11e7-916d-64894abcef7f.png">

Mainly I am interested in getting notifications about that one bot in the image (or the repository it contributes to). I see them in my dashboard, but I don't find a way to turn this into notifications .

**Comment by manosim** [comment]
Hi @a3f - I guess you will have to subscribe to that repo to get notifications about it. Currently gitify only displays GitHub notifications so can't subscribe to a user's actions unfortunately.
