### ISSUE TITLE
Gitify using "significant energy" while on battery

### ISSUE THREAD

**Issue by cbarraford** [manosim/gitify#318]
My macbook pro is displaying to me that gitify is using "significant energy", which seems odd for a great tiny tool. Any way to have it not drain my battery too much?

<img width="280" alt="screenshot 2017-09-11 11 02 15" src="https://user-images.githubusercontent.com/246180/30266819-dd6bc7a2-96e0-11e7-8a92-744040de3639.png">

**Comment by docwhat** [comment]
I'm guessing you had the "window" open?  The window has things like animations and blinking which use a lot of power (about 16 on my system).  With the window close it uses so little that it isn't measurable.

The fix to this is one or more of these:

- Remove unneeded animations.
- Run animations only once.
- Run animations only when the window is focused.

**Comment by manosim** [comment]
It looks like this is not the case in version 3.0.0 (updated Electron) - let me know if it's happening with the latest version and I can reopen this one! Thank you for reporting it!
