### ISSUE TITLE
Can't download mac app from http://gitify.io site

### ISSUE THREAD

**Issue by hdong92** [manosim/gitify#320]
When click on Mac OSX button, the API request fails so nothing is downloaded.

Here's the API that's returning 403: https://api.github.com/repos/manosim/gitify/releases/latest

Error message:
```
{
"message": "API rate limit exceeded for 62.60.99.4. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
"documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

**Comment by AriLFrankel** [comment]
This link works fine for me. Have you tried it again since then? If so, is this still an issue?

**Comment by hdong92** [comment]
I just tried it again, everything seems to be working fine now!
