### ISSUE TITLE
Logging out and in again doesn't work as expected

### ISSUE THREAD

**Issue by rafaelramalho19** [manosim/gitify#321]
I'm unable to log out of Gitify and log in a different account. It seems to always log in to the old account and doesn't prompt me again for the GitHub account.

Video: https://cl.ly/281x072F1X3p

**Comment by dctucker** [comment]
Just wanted to comment that this is somewhat concerning since it leaves the OAuth token in the logged-in system. The only way to truly log out is to revoke the token in my Github Authorized Applications settings.
