### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by victor-homyakov** [manosim/gitify#323]
Network errors are not processed, application throws its own error instead
![gitify 2017-10-31 11-15-04](https://user-images.githubusercontent.com/121449/32213673-39ea0b38-be2d-11e7-9738-f4c20bca9a03.png)

**Comment by taotaobujue88** [comment]
how to deal this problem?

**Comment by manosim** [comment]
That shouldn't be the case any more - let me know if this happens again and I'll be happy to reopen the issue 😄
