### ISSUE TITLE
Offer a first class toggle participating button

### ISSUE THREAD

**Issue by benjaminapetersen** [manosim/gitify#330]
Toggling participating is pretty handy, I do it often.  Ideally I wouldn't have to open settings to do so.

**Comment by benjaminapetersen** [comment]
Fixed or won't fix?
Thanks!  Just good to clarify when closing.

**Comment by manosim** [comment]
Sorry, thought I left a comment (went through all issues in the repo at once). I think that since v3 moves the app back to the tray icon, it would be better to keep it simple and leave that setting under the settings page.
