### ISSUE TITLE
Broken download link on the website (www.gitify.io)

### ISSUE THREAD

**Issue by bradzacher** [manosim/gitify#343]
The website's download link relies upon the github API.
However the Github API will rate limit and subsequently reject requests from an IP address.
This can be a problem if too many people use the public github api from the same WAN IP (i.e. from inside an organisation's network).

![image](https://user-images.githubusercontent.com/7462525/45048648-545bf980-b031-11e8-8405-9ee727a6490d.png)

Suggest adding an error message with a fallback in the case the request to the github API fails, rather than just showing nothing.

**Comment by alexbeletsky** [comment]
Is the project still alive?

<img width="580" alt="screen shot 2018-09-26 at 16 55 55" src="https://user-images.githubusercontent.com/304929/46088740-51c26f00-c1ad-11e8-867b-2e2e5c2c49ea.png">

**Comment by manosim** [comment]
This is now fixed 😄
