### ISSUE TITLE
Authentication Issues

### ISSUE THREAD

**Issue by DonRichards** [manosim/gitify#357]
Github no longer supports your browser when trying to authenticate for the first time.

![Screen Shot 2019-06-24 at 12 32 18 PM](https://user-images.githubusercontent.com/2738244/60036676-c1eb1c00-967d-11e9-9999-e801fa5021cf.jpg)

**Comment by JakeSidSmith** [comment]
This appears to be a duplicate of https://github.com/manosim/gitify/issues/355

**Comment by DonRichards** [comment]
Thanks for that!
