### ISSUE TITLE
UI for unsubscribing a PR notification?

### ISSUE THREAD

**Issue by junjizhi** [manosim/gitify#402]
I found I often click on the notification to go to the PR and press unsub button. It would be nice if I can mute the same series of notification through Gitify.

Is there a plan to support this feature?

**Comment by JakeSidSmith** [comment]
I'd never really thought about that before, but I often do the same. Would be real nice. 😊

**Comment by codebytere** [comment]
Seems pretty straightforward to potentially do so via [this endpoint](https://developer.github.com/v3/activity/notifications/#delete-a-thread-subscription) - i'd be happy to work on this potentially if that'd be something that would be acceptable to the project?

**Comment by manosim** [comment]
I think it's a great idea, I tend to do the same thing(click on a specific link/issue and then press "unsubscribe". I had a look yesterday and was wondering what would be the correct place for such a button from a UX point of view.

Could be before the "check" in light gray but that would take more space from the notification title? Any thoughts?

**Comment by codebytere** [comment]
Perhaps a circle slash octicon immediately to the left of the check? Perhaps we could make the window a tad wider to avoid removing too much text, but something like this?

<img width="516" alt="Screen Shot 2020-05-03 at 10 53 30 AM" src="https://user-images.githubusercontent.com/2036040/80921658-6cb37880-8d2c-11ea-91de-1fecf7b03169.png">

**Comment by junjizhi** [comment]
I saw the small unsub button in Gitify app today. This is awesome. Thanks for the quick turn-around!
