### ISSUE TITLE
Mark as read when clicking notification

### ISSUE THREAD

**Issue by aparajita** [manosim/gitify#412]
Gitify 3.0.5
macOS 10.15.5

When clicking a notification, it correctly takes me to the relevant place in github, but the corresponding item in Gitify is not marked as read.

**Comment by JakeSidSmith** [comment]
I've just upgraded and it appears to work fine for me. Does the notifications still appear after you hit the refresh icon?

**Comment by aparajita** [comment]
The point is I shouldn't have to manually refresh. 😁

**Comment by codebytere** [comment]
hmm - i'm on the same version and i've not had to manually refresh 🤔 do you have a gif or something demonstrating the behavior?

**Comment by aparajita** [comment]
Leave a comment again so I can record.

**Comment by JakeSidSmith** [comment]
> The point is I shouldn't have to manually refresh. 😁

The reason I asked was to make sure that they are actually marked as read, which they are, there is not a bug.

Gitify polls the notifications every 60 seconds. So they will disappear from the app within a minute at most.

Is what you are asking for optimistic updates?

**Comment by aparajita** [comment]
Yes, I see it eventually goes away. But I think you can know when the notification is clicked, in which case you might as well remove that item from the list. From a UX perspective it is expected.
