### ISSUE TITLE
[Feature request] Github discussion support

### ISSUE THREAD

**Issue by yubozhao** [manosim/gitify#424]
Thanks for the awesome tool!

As Github rolling out discussion feature to repos(https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more), it would be very nice to also have discussion support by Gitify.

**Comment by alavkx** [comment]
Seems Github discussions appear alongside other notifications (which is fine). Clicking on the discussion link dismissed the notification but does not open the link.

**Comment by codebytere** [comment]
Unfortunately this is a bug in the GitHub notifications API - the `url` field in the notification payload is never populated for some newer types of Notifications, discussion included. I filed it with the team when I was still an employee there, but there isn't anything that can be done about it on this end; when GitHub fixes it it'll automatically start working here.
