### ISSUE TITLE
How to quit menu bar app?

### ISSUE THREAD

**Issue by john-goldsmith** [manosim/gitify#432]
Is there a button/keyboard command to quit the app that doesn't involve going to Activity Monitor?

**Comment by JakeSidSmith** [comment]
On a Mac? `CMD + Q`

**Comment by john-goldsmith** [comment]
Ha, sure enough that works -- thanks.  I guess the hidden request here would be to include some sort of menu that explicitly indicates how to quit.  The patterns I typically see are a native menu or a graphical menu, both of which include the ability to quit.

Example of a native menu-only app with a quit option:

![image](https://user-images.githubusercontent.com/865588/88981829-b522f980-d27b-11ea-96bb-375d88ea175b.png)

Example of a UI app with an an overflow menu containing a quit option:

![image](https://user-images.githubusercontent.com/865588/88981909-dab00300-d27b-11ea-921e-122fc6162014.png)

Gitify which provides neither a native menu nor an overflow menu:

![image](https://user-images.githubusercontent.com/865588/88982124-51e59700-d27c-11ea-8047-324a2014aad6.png)

**Comment by bquorning** [comment]
If you click the cogwheel, there’s a `Quit` button.

<img width="505" alt="Gitify 'quit' button" src="https://user-images.githubusercontent.com/22333/91890684-26493880-ec90-11ea-8d7d-93ada2eb8707.png">

But from the screenshot _you_ posted, it looks like the cogwheel menu isn’t available before you’re signed in…

**Comment by manosim** [comment]
We now have a quit button on the sidebar for logged out users 😄 
Will go out with the next release - #467
