### ISSUE TITLE
Notification phrasing - "you have got x new notification(s)"

### ISSUE THREAD

**Issue by gavinsmith** [manosim/gitify#445]
<img width="346" alt="Screen Shot 2020-12-07 at 10 21 29 AM" src="https://user-images.githubusercontent.com/465932/101369252-12f0cf00-3876-11eb-9df9-fd4283e2eb80.png">

I can't see where this is implemented in the source, but I'd suggest a change to this string. "You have got..." is not proper, I'd expect simply "You have...". So, in pseudocode,

`You have [count] new [pluralize("notification", count)]`

Thanks for your consideration, happy to help if I can!

**Comment by JakeSidSmith** [comment]
This was recently changed: https://github.com/manosim/gitify/pull/436

I'm not sure if it has or when it will be released.

**Comment by gavinsmith** [comment]
Ah! Thanks, @JakeSidSmith!
