### ISSUE TITLE
v3.1.1 does not hide app icon in dock

### ISSUE THREAD

**Issue by julietkb** [manosim/gitify#448]
Have to downgrade to [v3.1.0](https://github.com/manosim/gitify/releases/download/v3.1.0/Gitify-3.1.0.dmg) to get the app to only show in the menubar and not the dock as well.

**Comment by manosim** [comment]
It looks like this happened when we updated Electron a while back. I've just opened #447 which should fix this issue and will publish 3.1.2 in a bit 😄

**Comment by manosim** [comment]
Closing this one as version 3.1.2 is now out 🎉 Thank you for letting me know!
