### ISSUE TITLE
Bug: Notification categories now fill the window incorrectly with v3.1.3

### ISSUE THREAD

**Issue by robert914** [manosim/gitify#458]
When you get a project notification, the project name banner is filling the window now:

![2020-12-15 at 10 11 AM](https://user-images.githubusercontent.com/214286/102233415-3d6a0a00-3ebe-11eb-90f0-6fe131516eea.jpg)

This didn't use to happen prior to v3.1.3.

Please fix. Thanks!

**Comment by crockpotveggies** [comment]
Confirmed, I am also experiencing this issue on MacOS 11.1.

**Comment by mlostekk** [comment]
Same here

**Comment by manosim** [comment]
Hi everyone, thank you so much for reporting this one -  this is now fixed and planning to release it later this week (hopefully tomorrow) along with some big changes as well (dark mode 😄 ). Apologies it took a bit longer, was trying to wrap up the migration from Redux to React Context which was a massive change and improvement going forward for Gitify. Stay tuned for version 4 🎉
