### ISSUE TITLE
Bug: Preview image broken v3.1.3

### ISSUE THREAD

**Issue by mlostekk** [manosim/gitify#459]
The preview images i broken in the notification (happening on 10.15.7 (19H114))

![image](https://user-images.githubusercontent.com/10534316/102330602-0a8d4800-3f8a-11eb-8e82-b59bc47094b8.png)

**Comment by robert914** [comment]
I see the same issue.
![2020-12-17 at 8 54 AM](https://user-images.githubusercontent.com/214286/102496521-7f718800-4045-11eb-9367-14a19cd1559f.jpg)

**Comment by mheob** [comment]
I can confirm this on macOS Big Sur (11.1).
