### ISSUE TITLE
UI issues on 3.1.13

### ISSUE THREAD

**Issue by maks-rafalko** [manosim/gitify#460]
This is how it looks like on Arch linux, Manjaro KDE:

![gitify](https://user-images.githubusercontent.com/3725595/102410734-03a21c00-4002-11eb-894d-d1331484e3ad.png)

1. popup window is always positioned on the top right corner
2. there are issues with CSS layout after the latest update (3.1.3)

Other linux distros has issues as well: https://github.com/manosim/gitify/issues/401

**Comment by JakeSidSmith** [comment]
I'd like to add that those CSS issues are not Linux specific. I've just updated on my Mac, and have the same detached repo name thing when there are few notifications.

**Comment by robert914** [comment]
Same issue previously reported: https://github.com/manosim/gitify/issues/458

**Comment by maks-rafalko** [comment]
Thanks, closing as duplicate
