### ISSUE TITLE
Provide universal binary that support both Intel and Apple Silicon

### ISSUE THREAD

**Issue by lumaxis** [manosim/gitify#472]
On my new M1 MacBook, I'm trying to avoid running any Intel code in compatibility mode with Rosetta 2. Therefore, it would be nice if there were a version of Gitify built for arm64.

There are now builds of Electron for arm64 but I'm not sure how exactly the building & bundling would work, e.g. if a universal binary that contains both archs is feasible.

**Comment by manosim** [comment]
We now have support for Apple Silicon (#475, #478) - the website has 2 download buttons (Intel + Apple Silicon) 🎉 https://gitify.io/
