### ISSUE TITLE
[Bug] Broken discussions links

### ISSUE THREAD

**Issue by Araxeus** [manosim/gitify#501]
When a notification comes from discussions section
gitify display the notification, but clicking it doesn't seem to do anything

for example, I just received a notification that I couldn't click,
opened github.com and the notification link was:
```json
"https://github.com/th-ch/youtube-music/discussions/240#discussioncomment-755596"
```

**Comment by Araxeus** [comment]
@codebytere hey thanks for answering this :)

Do you know if they are already aware of this or should I tell github support about this?

I love gitify and use it alot, but this is a really consistently annoying bug that I would really like fixed 😢

**Comment by codebytere** [comment]
@Araxeus i'd say you should report - the more people bring it up the faster they'll fix it, likely :)

**Comment by kumar303** [comment]
Since this is ultimately broken in Gitify, maybe keep this issue open until it's fixed upstream?
