### ISSUE TITLE
Cannot validate PAT when register with Github Enterprise

### ISSUE THREAD

**Issue by Uanid** [manosim/gitify#502]
<img width="510" alt="스크린샷 2021-05-31 오후 2 22 03" src="https://user-images.githubusercontent.com/35264628/120143792-c3cf9980-c21b-11eb-9131-464d3dfd476e.png">

## Setup:
- MacBook Air 2020 (M1)
- macOS Big Sur 11.4
- Gitify v4.2.1 and v4.2.0
- Github Enterprise Server (not cloud)

## Describe the issue:
When register new personal access token to gitify, Gitify always print messages like above.
Also I tested to Github Cloud, it works well.

**Comment by manosim** [comment]
This was fixed in #524 - thank you for reporting this @Uanid 👍
