### ISSUE TITLE
The version number didn't changed in package.json of the latest release

### ISSUE THREAD

**Issue by PolpOnline** [manosim/gitify#503]
Hi, I noticed that in the package.json of the latest release source code the version is still `4.2.0` and not `4.2.1`
This leads to `electron-builder` producing packages marked with a different version.
Here's the package.json of the release: https://github.com/manosim/gitify/blob/v4.2.1/package.json

**Comment by thompsonbrian** [comment]
@manosim This can be closed.

**Comment by blackcat-917** [comment]
The file package.json has been updated after tagging the release, and, therefore, the tarball provided in the release isn't updated. @thompsonbrian

**Comment by thompsonbrian** [comment]
@blackcat-917 Ah my mistake.  

I can confirm that you are correct:

```sh
 $ cat gitify-4.2.1/package.json | grep "version"
  "version": "4.2.0",
```

**Comment by codebytere** [comment]
Closed in https://github.com/manosim/gitify/commit/b716ccb858f98152e29b995dce53c4a944763791
