### ISSUE TITLE
Unable to find gitify in list of apps and neither on marketplace

### ISSUE THREAD

**Issue by ssbarnea** [manosim/gitify#511]
The FAQ does mention where to look for gitify and nothing regarding how to add it if is not installed. I tried to search for it on marketplace but there is no gitify: https://github.com/marketplace?query=gitify and the application itself does not have any link to send you to the github page where to install it.

**Comment by codebytere** [comment]
@ssbarnea in [Latest Release](https://github.com/manosim/gitify/releases/tag/v4.2.1)

**Comment by ssbarnea** [comment]
I think you misread the report: installing the desktop app was not the problem, the problem is that it does not communicate with github-gitify-app.

**Comment by JakeSidSmith** [comment]
@ssbarnea both the Gitify logo in the app (top left) and GitHub icon (bottom right) link to Gitify on GitHub where you can then access the releases, or can download from the website mentioned in the readme: https://github.com/manosim/gitify#download

Gitify also automatically checks for updates (iirc), so I'm not entirely sure why you'd need to access the downloads if you're already running the app.

Can you expand on what you're trying to achieve? 😊

**Comment by ssbarnea** [comment]
App on Macos:
![](https://sbarnea.com/ss/Screen-Shot-2021-08-16-14-57-33.11.png)

Until I did logout and logged in again I was not able to do anything and the app was not giving any hints regarding what was going wrong.

**Comment by JakeSidSmith** [comment]
Ah, so the issue was that the error messaging was not very useful? I'd agree with you there.

Had you disabled Gitify's access of your GitHub info?

**Comment by ssbarnea** [comment]
I do not remember doing it but I do not rule out this as being the case. I think we should display the HTTP error message we get below the error message instead of just the generic one. A http error code should give someone a hint.

I would even mention that logging-out/in may help address the issue.

**Comment by JakeSidSmith** [comment]
I assume we probably also get back some useful error message from GitHub, but I haven't had a look myself for a while.
