### ISSUE TITLE
Option to turn off "That's amazing!" etc.

### ISSUE THREAD

**Issue by samsrabin** [manosim/gitify#513]
I know I sound like a stick in the mud, but the emojis and messages like "That's amazing" when there are no new notifications… I find them a bit patronizing. Maybe not the right word? But they bring a vibe that doesn't really work for me. I would love to have the option to turn off that personality. Thanks for considering!

**Comment by hughlilly** [comment]
Yep, I agree that the widespread infantilisation of users is really boring and in the case of an app like this serves no purpose.
