### ISSUE TITLE
callback

### ISSUE THREAD

**Issue by eliekh05** [manosim/gitify#528]
gitify it is giving me this is callback page nothing to see here

**Comment by DTTerastar** [comment]
Yeah, the flow to login via github doesn't work anymore.  You get to the callback and then get stuck.

**Comment by ppizarror** [comment]
Same issue here, I cannot login using my account. Using MacOS 11.6.1

**Comment by Kirill-Shklyarenko** [comment]
+

**Comment by manosim** [comment]
This has been fixed in v4.3.1 thanks to @yyar 🎉
