### ISSUE TITLE
Irrelevant notifications

### ISSUE THREAD

**Issue by karimStekelenburg** [manosim/gitify#562]
First of all, love this app. Keeping track of GH notifications always was a pain for me, but not anymore.

However, I've noticed I'm getting quite a few notifications about issues that have been resolved and PRs that are already merged. These notifications are of little value to me and just cause distractions.

That being said, this might be due to a lack of understanding of how Gitify works on my end. If a GH notification hasn't been marked as `done`, will Gitify notify me about it from time to time? If so, it would be nice to have a setting that makes sure it only notifies me about new/real-time-incoming GH notifications.

**Comment by JakeSidSmith** [comment]
Hey, @karimStekelenburg. Gitify notifies you about anything you have chosen to be notified about in GitHub.

You can adjust your overall notification setting [on GitHub](https://github.com/settings/notifications).

If you don't want to be notified about certain activity in a repo you can watch/unwatch/get notified only for mentioned and things you're participating in from the dropdown next to the fork button.

<img width="165" alt="Screen Shot 2023-01-26 at 18 08 53" src="https://user-images.githubusercontent.com/5850625/214915634-d2101604-17da-47ed-82ed-ef32f5319d74.png">

If you don't want to receive notifications from a specific issue/pull request you were following you'll need to hit the unsubscribe button in the right-hand sidebar. 😊 

<img width="321" alt="Screen Shot 2023-01-26 at 18 07 36" src="https://user-images.githubusercontent.com/5850625/214914822-d145d1e6-d1bb-4aaf-a1b7-ad54f70f5188.png">

If you haven't marked a notification as "read", then it will continue to appear in Gitify as it essentially displays the same list of notifications as [in GitHub](https://github.com/notifications) (with the addition of only displaying things you're participating in if you have that option selected in Gitify).

If you want to mark a notification as read when you click on it through Gitify you can enable "On Click, Mark as Read" in Gitify settings, though this won't stop you from watching that repo or being subscribed to that issue/pull request.

**Comment by karimStekelenburg** [comment]
Thanks, @JakeSidSmith!
I figured this was due to my bad notification hygiene. Didn't know about the mark as read on click feature though. That should solve my problem :)
